#!/bin/sh
#
cd /usr/local/share/cacti/cli
if [ $# -ne 1 ]
then
	echo "usage: $0 rtra"
	exit
fi
host=$1
# cisco_router=`php add_device.php --host-templates | awk '/Cisco Router$/ {print $1}'`
# if php add_device.php $cisco_router $host $host ietf70vancouver 2 0
cisco_router=`php add_device.php --list-host-templates | awk '/Cisco Router$/ {print $1}'`
if php add_device.php --description=$host --ip=$host --template=$cisco_router --version=3 --username=netdisco --password="Disco stu does not advertise." --authproto=SHA --privproto='[None]' --avail=snmp

then
	id=`php add_graphs.php --list-hosts | awk "\\$2 == \"$host\" {print \\$1}"`
	cpu_util=`php add_graphs.php --list-graph-templates | awk '/Cisco - CPU Usage$/ {print $1}'`
	# Cisco CPU utilization
	php add_graphs.php --graph-type=cg --graph-template-id=$cpu_util --host-id=$id
fi
