#!/bin/sh
#
# Script run out of cron to generate AP config matrix.
#
# $Id$
#
cd /usr/home/fenner/src/ap2k
./apconf > /usr/local/www/data/ap/conf/index.new.html
mv /usr/local/www/data/ap/conf/index.new.html /usr/local/www/data/ap/conf/index.html
