#!/bin/sh
#
cd /usr/local/share/cacti
if [ $# -ne 1 ]
then
	echo "usage: $0 apNN"
	exit
fi
host=$1
cisco_router=`php add_device.php --host-templates | awk '/Cisco Router$/ {print $1}'`
if php add_device.php $cisco_router $host $host ietf70vancouver 2 0
then
	id=`php add_graphs.php --list-hosts | awk "\\$2 == \"$host\" {print \\$1}"`
	echo Hostname $host Cacti ID $id
	# Cisco CPU utilization
	php add_graphs.php --graph-type cg --graph-template-id 18 --host-id $id
	# Add per-interface graphs
	/home/fenner/src/cacti/gadd-both $id
fi
