#!/bin/sh
cd /usr/local/share/cacti
#hotelaplist=$(php add_graphs.php --list-hosts | awk '$2 ~ /^ap_/ {print $1}')
#for i in $hotelaplist
#do
#	echo Hotel AP: $i
#	/home/fenner/src/cacti/gadd-Radio0 $i
#done
ouraplist=$(php add_graphs.php --list-hosts | awk '$2 ~ /^ap[0-9]*/ {print $1}')
for i in $ouraplist
do
	echo Our AP: $i
	/home/fenner/src/cacti/gadd-both $i
done
